### ISSUE TITLE
【プロジェクト】サンプルデータが作成されない

### ISSUE THREAD

**Issue by yootani** [syssqu/sigohaka#100]
## 概要
プロジェクトのバリデーションチェックにサンプルデータがひっかかり、サンプルデータが作成されない。

## 問題点
プロジェクトの終了月が空白で登録できない。

**Comment by yootani** [comment]
## 一時対応
プロジェクトのサンプルデータをコメントアウトし、一時的に対応。

**Comment by njsekay** [comment]
## 原因
プロジェクト作成時に実施される年月の整合性チェックの不備

## 対応
終了日が入力されている場合のみ、整合性チェックを実施するよう修正。
