### ISSUE TITLE
印鑑の画像が表示されない

### ISSUE THREAD

**Issue by ko-taka** [syssqu/sigohaka#29]
## 概要
各印刷用画面の印鑑の画像が表示されない.

**Comment by njsekay** [comment]
印鑑データを出力するには、以下にpngを配置する必要がある。
◆印鑑データの格納フォルダ
sigohaka\app\assets\images\

その際、ファイルはメールの@より左を指定すること。
例えばメールアドレスが「j-nakamura@sys-square.co.jp」であれば、ファイル名を「j-nakamura.png」とする。
