### ISSUE TITLE
勤務情報修正の挙動がおかしい

### ISSUE THREAD

**Issue by ko-taka** [syssqu/sigohaka#33]
## 概要
・勤務情報修正に飛んだ最初、勤怠パターンを選択しても、出退勤に時刻が入力されない.
　上記の後で更新ボタンを押下し、遷移してきた後に勤怠パターンを選択すると入力される.
・出退勤に時刻が入力された状態で、自動計算ボタンを押下するとError statusに飛ばされる.

**Comment by njsekay** [comment]
## 原因
対象勤務パターンの抽出条件として、勤務パターン.id = 画面で選択された勤務パターンのコードが指定されていたため。

## 対応内容
対象勤務パターンの抽出条件を
>勤務パターン.コード = 画面で選択された勤務パターンのコード
に変更
