### ISSUE TITLE
住宅手当申請のメソッドの未定義

### ISSUE THREAD

**Issue by gagw** [syssqu/sigohaka#36]
## 概要
住宅手当申請のページに移動すると、sigohaka/app/views/shared/_paper_proc.html.slim where line #7のメソッドが未定義である。クラスが無いとエラー画面が出る。

**Comment by njsekay** [comment]
# 原因
@usersや@kintai_header等の変数が初期化されていなかったため。

# 対応
@usersや@kintai_header等の変数を初期化。
