### ISSUE TITLE
勤務パターンの数

### ISSUE THREAD

**Issue by ko-taka** [syssqu/sigohaka#39]
## 概要
登録できる勤務パターンが3つしかない.

**Comment by njsekay** [comment]
## 原因
登録できる勤務パターンは１ユーザーにつき５個固定としている。
対象ユーザーのインスタンスがxxxだとして、テストデータ「lib/sample_data.rake」に以下を追加

> xxx.kinmu_patterns.create!(code: "4")
xxx.kinmu_patterns.create!(code: "5")
xxx.kinmu_patterns.create!(code: "*")

## 特記事項
運用開始時における事前投入データとして注意が必要。
