### ISSUE TITLE
プロジェクト編集　役割と工程の入力欄

### ISSUE THREAD

**Issue by gagw** [syssqu/sigohaka#42]
## 概要
プロジェクトの編集画面での、役割と工程の欄について。下に番号の候補があるのに、入力欄では自由に書き込むことが出来るのですが、これは仕様なのでしょうか。

**Comment by njsekay** [comment]
本来はテキスト入力ではなくて、選択ボックスにするべきやろうな。保留扱いにしときましょう。

**Comment by njsekay** [comment]
セレクトボックスではなくチェックボックスにて対応。
→#134 により対応のため、本issueはクローズ
